---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments à passer à nosetests
      type: string
      # tu peux ajuster ici si besoin
      default: "-v --with-spec --spec-color --with-coverage --cover-package=service"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -euo pipefail

        # venv local à la step (évite le warning "pip as root")
        python -m venv .venv
        source .venv/bin/activate

        # pip à jour + deps
        python -m pip install --upgrade pip wheel
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        # Au cas où requirements.txt n'inclut pas ces paquets :
        pip install nose nose-spec coverage >/dev/null 2>&1 || true

        # tests
        nosetests $(params.args)
